/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    cursor?: string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CursorPageDtoOfGoalDto"];
                        "application/json": components["schemas"]["CursorPageDtoOfGoalDto"];
                        "text/json": components["schemas"]["CursorPageDtoOfGoalDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGoalRequest"];
                    "text/json": components["schemas"]["CreateGoalRequest"];
                    "application/*+json": components["schemas"]["CreateGoalRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoalDto"];
                        "application/json": components["schemas"]["GoalDto"];
                        "text/json": components["schemas"]["GoalDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoalDto"];
                        "application/json": components["schemas"]["GoalDto"];
                        "text/json": components["schemas"]["GoalDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGoalRequest"];
                    "text/json": components["schemas"]["UpdateGoalRequest"];
                    "application/*+json": components["schemas"]["UpdateGoalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoalDto"];
                        "application/json": components["schemas"]["GoalDto"];
                        "text/json": components["schemas"]["GoalDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}/terminal-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TerminalPreviewRequest"];
                    "text/json": components["schemas"]["TerminalPreviewRequest"];
                    "application/*+json": components["schemas"]["TerminalPreviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TerminalPreviewDto"];
                        "application/json": components["schemas"]["TerminalPreviewDto"];
                        "text/json": components["schemas"]["TerminalPreviewDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TerminalCommandRequest"];
                    "text/json": components["schemas"]["TerminalCommandRequest"];
                    "application/*+json": components["schemas"]["TerminalCommandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoalDto"];
                        "application/json": components["schemas"]["GoalDto"];
                        "text/json": components["schemas"]["GoalDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    cursor?: string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CursorPageDtoOfProjectDto"];
                        "application/json": components["schemas"]["CursorPageDtoOfProjectDto"];
                        "text/json": components["schemas"]["CursorPageDtoOfProjectDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                    "text/json": components["schemas"]["CreateProjectRequest"];
                    "application/*+json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectDto"];
                        "application/json": components["schemas"]["ProjectDto"];
                        "text/json": components["schemas"]["ProjectDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectDto"];
                        "application/json": components["schemas"]["ProjectDto"];
                        "text/json": components["schemas"]["ProjectDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                    "text/json": components["schemas"]["UpdateProjectRequest"];
                    "application/*+json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectDto"];
                        "application/json": components["schemas"]["ProjectDto"];
                        "text/json": components["schemas"]["ProjectDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/terminal-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TerminalPreviewRequest"];
                    "text/json": components["schemas"]["TerminalPreviewRequest"];
                    "application/*+json": components["schemas"]["TerminalPreviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TerminalPreviewDto"];
                        "application/json": components["schemas"]["TerminalPreviewDto"];
                        "text/json": components["schemas"]["TerminalPreviewDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TerminalCommandRequest"];
                    "text/json": components["schemas"]["TerminalCommandRequest"];
                    "application/*+json": components["schemas"]["TerminalCommandRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectDto"];
                        "application/json": components["schemas"]["ProjectDto"];
                        "text/json": components["schemas"]["ProjectDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    cursor?: string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CursorPageDtoOfTaskDto"];
                        "application/json": components["schemas"]["CursorPageDtoOfTaskDto"];
                        "text/json": components["schemas"]["CursorPageDtoOfTaskDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                    "text/json": components["schemas"]["CreateTaskRequest"];
                    "application/*+json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                    "text/json": components["schemas"]["UpdateTaskRequest"];
                    "application/*+json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteTaskRequest"];
                    "text/json": components["schemas"]["CompleteTaskRequest"];
                    "application/*+json": components["schemas"]["CompleteTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DropTaskRequest"];
                    "text/json": components["schemas"]["DropTaskRequest"];
                    "application/*+json": components["schemas"]["DropTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RestoreTaskRequest"];
                    "text/json": components["schemas"]["RestoreTaskRequest"];
                    "application/*+json": components["schemas"]["RestoreTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiProblemDto"];
                        "application/json": components["schemas"]["ApiProblemDto"];
                        "text/json": components["schemas"]["ApiProblemDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodayDto"];
                        "application/json": components["schemas"]["TodayDto"];
                        "text/json": components["schemas"]["TodayDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequestOtpDto"];
                    "text/json": components["schemas"]["RequestOtpDto"];
                    "application/*+json": components["schemas"]["RequestOtpDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyOtpDto"];
                    "text/json": components["schemas"]["VerifyOtpDto"];
                    "application/*+json": components["schemas"]["VerifyOtpDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiProblemDto: {
            type: string;
            title: string;
            /** Format: int32 */
            status: number | string;
            code: string;
            messageKey: string;
            retryable: boolean;
            traceId: string;
            correlationId: string;
            detail: null | string;
            errors: null | {
                [key: string]: string[];
            };
            /** Format: uuid */
            entityId: null | string;
            /** Format: int64 */
            expectedVersion: null | number | string;
            /** Format: int64 */
            currentVersion: null | number | string;
        };
        CompleteTaskRequest: {
            /** Format: int64 */
            expectedVersion: number | string;
            /** Format: date */
            completedForLocalDate: string;
        };
        CreateGoalRequest: {
            title: string;
            desiredOutcome: string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: null | string;
        };
        CreateProjectRequest: {
            title: string;
            completionMeaning: null | string;
            /** Format: uuid */
            goalId: null | string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: null | string;
        };
        CreateTaskRequest: {
            title: string;
            description: null | string;
            /** Format: uuid */
            goalId: null | string;
            /** Format: uuid */
            projectId: null | string;
            /** Format: date */
            plannedDate: null | string;
            /** Format: date */
            deadline: null | string;
            /** Format: uuid */
            sequenceId: null | string;
            /** Format: int32 */
            sequenceOrder: null | number | string;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            phoneNumber: string;
            displayName: null | string;
            setupComplete: boolean;
        };
        CursorPageDtoOfGoalDto: {
            items: components["schemas"]["GoalDto"][];
            page: components["schemas"]["PageInfoDto"];
        };
        CursorPageDtoOfProjectDto: {
            items: components["schemas"]["ProjectDto"][];
            page: components["schemas"]["PageInfoDto"];
        };
        CursorPageDtoOfTaskDto: {
            items: components["schemas"]["TaskDto"][];
            page: components["schemas"]["PageInfoDto"];
        };
        DropTaskRequest: {
            /** Format: int64 */
            expectedVersion: number | string;
        };
        GoalDto: {
            /** Format: uuid */
            id: string;
            title: string;
            desiredOutcome: string;
            status: string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: string;
            reviewDateSource: string;
            /** Format: date-time */
            lastContinuationDecisionAt: null | string;
            source: string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            terminalAt: null | string;
        };
        PageInfoDto: {
            nextCursor: null | string;
            hasMore: boolean;
        };
        ProjectDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId: null | string;
            title: string;
            completionMeaning: null | string;
            status: string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: string;
            reviewDateSource: string;
            source: string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            terminalAt: null | string;
        };
        RequestOtpDto: {
            phoneNumber: string;
            purpose: string;
        };
        RestoreTaskRequest: {
            /** Format: int64 */
            expectedVersion: number | string;
            /** Format: date */
            plannedDate: null | string;
        };
        TaskDependencyDto: {
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            /** Format: int64 */
            version: number | string;
        };
        TaskDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            goalId: null | string;
            /** Format: uuid */
            projectId: null | string;
            title: string;
            description: null | string;
            status: string;
            /** Format: date */
            plannedDate: null | string;
            /** Format: date */
            deadline: null | string;
            /** Format: uuid */
            sequenceId: null | string;
            /** Format: int32 */
            sequenceOrder: null | number | string;
            isBlocked: boolean;
            blockedBy: components["schemas"]["TaskDependencyDto"][];
            /** Format: date */
            completedForLocalDate: null | string;
            source: string;
            /** Format: int64 */
            version: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            terminalAt: null | string;
        };
        TerminalBlockerDto: {
            resourceType: string;
            /** Format: uuid */
            resourceId: string;
            status: string;
            /** Format: int64 */
            version: number | string;
        };
        TerminalCommandRequest: {
            targetStatus: string;
            /** Format: int64 */
            expectedVersion: number | string;
            previewHash: string;
        };
        TerminalPreviewDto: {
            /** Format: uuid */
            entityId: string;
            entityType: string;
            currentStatus: string;
            targetStatus: string;
            /** Format: int64 */
            expectedVersion: number | string;
            canApply: boolean;
            blockers: components["schemas"]["TerminalBlockerDto"][];
            previewHash: string;
        };
        TerminalPreviewRequest: {
            targetStatus: string;
            /** Format: int64 */
            expectedVersion: number | string;
        };
        TodayDto: {
            /** Format: date */
            localDate: string;
            tasks: components["schemas"]["TaskDto"][];
        };
        UpdateGoalRequest: {
            title: string;
            desiredOutcome: string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: null | string;
            /** Format: int64 */
            expectedVersion: number | string;
        };
        UpdateProjectRequest: {
            title: string;
            completionMeaning: null | string;
            /** Format: uuid */
            goalId: null | string;
            /** Format: date */
            targetDate: null | string;
            /** Format: date */
            reviewDate: null | string;
            /** Format: int64 */
            expectedVersion: number | string;
        };
        UpdateTaskRequest: {
            title: string;
            description: null | string;
            /** Format: uuid */
            goalId: null | string;
            /** Format: uuid */
            projectId: null | string;
            /** Format: date */
            plannedDate: null | string;
            /** Format: date */
            deadline: null | string;
            /** Format: uuid */
            sequenceId: null | string;
            /** Format: int32 */
            sequenceOrder: null | number | string;
            /** Format: int64 */
            expectedVersion: number | string;
        };
        VerifyOtpDto: {
            phoneNumber: string;
            code: string;
            purpose: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
