// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TidySense.Data;

#nullable disable

namespace TidySense.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003142533_Step8PlanningFoundation")]
    partial class Step8PlanningFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TidySense.Models.ActionConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlanningDraftId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlanningDraftRevision")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreviewJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ReconcileSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanningDraftId");

                    b.HasIndex("ReconcileSessionId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ActionConfirmations", t =>
                        {
                            t.HasCheckConstraint("CK_ActionConfirmations_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_ActionConfirmations_Status", "\"Status\" IN ('CREATED', 'SUBMITTED', 'RESOLVED', 'EXPIRED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_ActionConfirmations_Subject", "(\"ReconcileSessionId\" IS NOT NULL AND \"PlanningDraftId\" IS NULL AND \"PlanningDraftRevision\" IS NULL) OR (\"ReconcileSessionId\" IS NULL AND \"PlanningDraftId\" IS NOT NULL AND \"PlanningDraftRevision\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TidySense.Models.CaptureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status", "CreatedAt", "Id");

                    b.ToTable("Captures", null, t =>
                        {
                            t.HasCheckConstraint("CK_Captures_Resolution", "(\"Status\" = 'UNRESOLVED' AND \"ResolvedAt\" IS NULL) OR (\"Status\" IN ('RESOLVED', 'DISCARDED') AND \"ResolvedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Captures_Source", "\"Source\" IN ('MANUAL', 'SYSTEM_MIGRATED')");

                            t.HasCheckConstraint("CK_Captures_Status", "\"Status\" IN ('UNRESOLVED', 'RESOLVED', 'DISCARDED')");

                            t.HasCheckConstraint("CK_Captures_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.CommandResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdempotencyRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyRecordId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CommandResults", t =>
                        {
                            t.HasCheckConstraint("CK_CommandResults_Status", "\"Status\" IN ('SUCCEEDED', 'CONFLICTED', 'FAILED_FINAL', 'FAILED_RETRYABLE')");
                        });
                });

            modelBuilder.Entity("TidySense.Models.DomainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommandResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfirmationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReconcileSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("RuleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("CommandResultId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAt");

                    b.ToTable("DomainEvents", t =>
                        {
                            t.HasCheckConstraint("CK_DomainEvents_Actor", "\"Actor\" IN ('USER', 'SYSTEM_DETERMINISTIC')");

                            t.HasCheckConstraint("CK_DomainEvents_AggregateVersion", "\"AggregateVersion\" > 0");

                            t.HasCheckConstraint("CK_DomainEvents_EventVersion", "\"EventVersion\" > 0");

                            t.HasCheckConstraint("CK_DomainEvents_PayloadObject", "jsonb_typeof(\"PayloadJson\") = 'object'");

                            t.HasCheckConstraint("CK_DomainEvents_PayloadSize", "octet_length(\"PayloadJson\"::text) <= 4096");
                        });
                });

            modelBuilder.Entity("TidySense.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesiredOutcome")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastContinuationDecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewDateSource")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt", "Id");

                    b.HasIndex("UserId", "Status", "ReviewDate");

                    b.ToTable("Goals", t =>
                        {
                            t.HasCheckConstraint("CK_Goals_ReviewDateSource", "\"ReviewDateSource\" IN ('USER', 'SYSTEM_DEFAULT', 'MIGRATED_DEFAULT')");

                            t.HasCheckConstraint("CK_Goals_Source", "\"Source\" IN ('MANUAL', 'AI_ASSISTED', 'SYSTEM_MIGRATED')");

                            t.HasCheckConstraint("CK_Goals_Status", "\"Status\" IN ('ACTIVE', 'ACHIEVED', 'ABANDONED')");

                            t.HasCheckConstraint("CK_Goals_TerminalState", "(\"Status\" = 'ACTIVE' AND \"TerminalAt\" IS NULL) OR (\"Status\" IN ('ACHIEVED', 'ABANDONED') AND \"TerminalAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Goals_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", t =>
                        {
                            t.HasCheckConstraint("CK_IdempotencyRecords_Status", "\"Status\" IN ('IN_PROGRESS', 'SUCCEEDED', 'CONFLICTED', 'FAILED_FINAL', 'FAILED_RETRYABLE')");
                        });
                });

            modelBuilder.Entity("TidySense.Models.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeDigest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPhone", "Purpose", "CreatedAt");

                    b.ToTable("OtpChallenges", t =>
                        {
                            t.HasCheckConstraint("CK_OtpChallenges_AttemptCount", "\"AttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.OtpRateEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Kind", "KeyDigest", "CreatedAt");

                    b.ToTable("OtpRateEvents");
                });

            modelBuilder.Entity("TidySense.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("OutboxMessages", t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_AttemptCount", "\"AttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.PlanningAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientAttemptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextBuilderVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContextFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ContextGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ContextProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GeneratorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Intention")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanningAttempts_OneInFlightPerUser")
                        .HasFilter("\"Status\" IN ('QUEUED', 'RUNNING')");

                    b.HasIndex("UserId", "ClientAttemptId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PlanningAttempts", t =>
                        {
                            t.HasCheckConstraint("CK_PlanningAttempts_Completion", "(\"Status\" IN ('QUEUED', 'RUNNING')) = (\"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_PlanningAttempts_ContextExclusive", "NOT (\"ContextGoalId\" IS NOT NULL AND \"ContextProjectId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanningAttempts_ManifestObject", "jsonb_typeof(\"ContextManifestJson\") = 'object'");

                            t.HasCheckConstraint("CK_PlanningAttempts_Outcome", "(\"Status\" = 'SUCCEEDED') = (\"DraftId\" IS NOT NULL) AND (\"Status\" = 'FAILED') = (\"FailureCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanningAttempts_Status", "\"Status\" IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("TidySense.Models.PlanningDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ContextGoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedConfirmationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanningDrafts_OneReviewablePerUser")
                        .HasFilter("\"Status\" = 'REVIEWABLE'");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("PlanningDrafts", t =>
                        {
                            t.HasCheckConstraint("CK_PlanningDrafts_ContextExclusive", "NOT (\"ContextGoalId\" IS NOT NULL AND \"ContextProjectId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanningDrafts_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_PlanningDrafts_Revision", "\"CurrentRevision\" > 0");

                            t.HasCheckConstraint("CK_PlanningDrafts_Status", "\"Status\" IN ('REVIEWABLE', 'SUPERSEDED', 'EXPIRED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_PlanningDrafts_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.PlanningDraftRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Revision")
                        .IsUnique();

                    b.ToTable("PlanningDraftRevisions", t =>
                        {
                            t.HasCheckConstraint("CK_PlanningDraftRevisions_ContentObject", "jsonb_typeof(\"ContentJson\") = 'object'");

                            t.HasCheckConstraint("CK_PlanningDraftRevisions_Origin", "\"Origin\" IN ('GENERATED', 'USER_EDIT')");

                            t.HasCheckConstraint("CK_PlanningDraftRevisions_Revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.PlanningFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SourcePlanningAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "UserId");

                    b.HasIndex("ProjectId", "UserId");

                    b.HasIndex("UserId", "GoalId", "Status");

                    b.HasIndex("UserId", "ProjectId", "Status");

                    b.ToTable("PlanningFacts", t =>
                        {
                            t.HasCheckConstraint("CK_PlanningFacts_FactType", "\"FactType\" IN ('UNAVAILABLE_WEEKDAY', 'UNAVAILABLE_DATE', 'UNAVAILABLE_DATE_RANGE', 'AVAILABLE_DEVICE', 'CURRENT_LEVEL', 'LEARNING_FOCUS', 'EXCLUDED_PATH')");

                            t.HasCheckConstraint("CK_PlanningFacts_Lifecycle", "(\"Status\" = 'REMOVED') = (\"RemovedAt\" IS NOT NULL) AND (\"Status\" = 'EXPIRED') = (\"ExpiredAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanningFacts_OneScope", "(\"GoalId\" IS NOT NULL) <> (\"ProjectId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanningFacts_Source", "\"Source\" IN ('USER_EXPLICIT', 'USER_CONFIRMED_AI_EXTRACTION')");

                            t.HasCheckConstraint("CK_PlanningFacts_Status", "\"Status\" IN ('ACTIVE', 'EXPIRED', 'REMOVED')");

                            t.HasCheckConstraint("CK_PlanningFacts_Strength", "\"Strength\" IN ('SOFT', 'INFORMATIONAL') OR (\"Strength\" = 'HARD' AND \"FactType\" IN ('UNAVAILABLE_WEEKDAY', 'UNAVAILABLE_DATE', 'UNAVAILABLE_DATE_RANGE'))");

                            t.HasCheckConstraint("CK_PlanningFacts_ValueObject", "jsonb_typeof(\"ValueJson\") = 'object'");

                            t.HasCheckConstraint("CK_PlanningFacts_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompletionMeaning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewDateSource")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "UserId");

                    b.HasIndex("UserId", "CreatedAt", "Id");

                    b.HasIndex("UserId", "Status", "ReviewDate");

                    b.ToTable("Projects", t =>
                        {
                            t.HasCheckConstraint("CK_Projects_ReviewDateSource", "\"ReviewDateSource\" IN ('USER', 'SYSTEM_DEFAULT', 'MIGRATED_DEFAULT')");

                            t.HasCheckConstraint("CK_Projects_Source", "\"Source\" IN ('MANUAL', 'AI_ASSISTED', 'SYSTEM_MIGRATED')");

                            t.HasCheckConstraint("CK_Projects_Status", "\"Status\" IN ('ACTIVE', 'COMPLETED', 'STOPPED')");

                            t.HasCheckConstraint("CK_Projects_TerminalState", "(\"Status\" = 'ACTIVE' AND \"TerminalAt\" IS NULL) OR (\"Status\" IN ('COMPLETED', 'STOPPED') AND \"TerminalAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Projects_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.ReconcileFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EvidenceQuality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("FactVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ObservedMetrics")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string[]>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ReconcileFacts", t =>
                        {
                            t.HasCheckConstraint("CK_ReconcileFacts_MetricsObject", "jsonb_typeof(\"ObservedMetrics\") = 'object'");
                        });
                });

            modelBuilder.Entity("TidySense.Models.ReconcilePrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LocalDate")
                        .IsUnique();

                    b.ToTable("ReconcilePrompts", t =>
                        {
                            t.HasCheckConstraint("CK_ReconcilePrompts_State", "\"State\" IN ('DISMISSED', 'SKIPPED')");

                            t.HasCheckConstraint("CK_ReconcilePrompts_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.ReconcileSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionableBacklogCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DegradedMode")
                        .HasColumnType("boolean");

                    b.Property<int>("FactSnapshotVersion")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int?>("OldestUnresolvedAgeDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("ReviewDueCount")
                        .HasColumnType("integer");

                    b.Property<string>("RulesCatalogVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("UnresolvedCaptureCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReconcileSessions_OneOpenPerUser")
                        .HasFilter("\"Status\" = 'OPEN'");

                    b.HasIndex("UserId", "OpenedAt");

                    b.ToTable("ReconcileSessions", t =>
                        {
                            t.HasCheckConstraint("CK_ReconcileSessions_Completion", "(\"Status\" = 'OPEN' AND \"CompletedAt\" IS NULL) OR (\"Status\" <> 'OPEN' AND \"CompletedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ReconcileSessions_Counts", "\"ActionableBacklogCount\" >= 0 AND \"ReviewDueCount\" >= 0 AND \"UnresolvedCaptureCount\" >= 0");

                            t.HasCheckConstraint("CK_ReconcileSessions_Severity", "\"Severity\" IN ('NONE', 'LIGHT', 'MEDIUM', 'RECOVERY')");

                            t.HasCheckConstraint("CK_ReconcileSessions_Status", "\"Status\" IN ('OPEN', 'COMPLETED', 'ABANDONED', 'EXPIRED')");

                            t.HasCheckConstraint("CK_ReconcileSessions_TriggerType", "\"TriggerType\" IN ('MANUAL', 'PROMPT')");

                            t.HasCheckConstraint("CK_ReconcileSessions_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContinuationOfRoutineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("EffectiveFromLocalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveUntilLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("MaterializedThroughLocalDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecurrenceDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecurrenceTimezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<TimeOnly[]>("TimesOfDay")
                        .IsRequired()
                        .HasColumnType("time without time zone[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContinuationOfRoutineId")
                        .IsUnique()
                        .HasFilter("\"ContinuationOfRoutineId\" IS NOT NULL");

                    b.HasIndex("GoalId", "UserId");

                    b.HasIndex("ProjectId", "UserId");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "CreatedAt", "Id");

                    b.HasIndex("UserId", "GoalId", "Status");

                    b.HasIndex("UserId", "ProjectId", "Status");

                    b.ToTable("Routines", t =>
                        {
                            t.HasCheckConstraint("CK_Routines_ContinuationNotSelf", "\"ContinuationOfRoutineId\" IS NULL OR \"ContinuationOfRoutineId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_Routines_EffectiveRange", "\"EffectiveUntilLocalDate\" IS NULL OR \"EffectiveUntilLocalDate\" >= \"EffectiveFromLocalDate\" - 1");

                            t.HasCheckConstraint("CK_Routines_ParentExclusive", "NOT (\"GoalId\" IS NOT NULL AND \"ProjectId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Routines_RecurrenceObject", "jsonb_typeof(\"RecurrenceDefinition\") = 'object'");

                            t.HasCheckConstraint("CK_Routines_Source", "\"Source\" IN ('MANUAL', 'AI_ASSISTED', 'SYSTEM_MIGRATED')");

                            t.HasCheckConstraint("CK_Routines_Status", "\"Status\" IN ('ACTIVE', 'STOPPED')");

                            t.HasCheckConstraint("CK_Routines_StoppedState", "(\"Status\" = 'ACTIVE' AND \"StoppedAt\" IS NULL AND \"EffectiveUntilLocalDate\" IS NULL) OR (\"Status\" = 'STOPPED' AND \"StoppedAt\" IS NOT NULL AND \"EffectiveUntilLocalDate\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Routines_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.RoutineOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ScheduledLocalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("ScheduledLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId", "ScheduledLocalDate")
                        .IsUnique()
                        .HasDatabaseName("IX_RoutineOccurrences_UntimedIdentity")
                        .HasFilter("\"ScheduledLocalTime\" IS NULL");

                    b.HasIndex("Status", "ScheduledLocalDate");

                    b.HasIndex("RoutineId", "ScheduledLocalDate", "ScheduledLocalTime")
                        .IsUnique()
                        .HasDatabaseName("IX_RoutineOccurrences_TimedIdentity")
                        .HasFilter("\"ScheduledLocalTime\" IS NOT NULL");

                    b.ToTable("RoutineOccurrences", t =>
                        {
                            t.HasCheckConstraint("CK_RoutineOccurrences_Resolution", "(\"Status\" = 'PENDING' AND \"ResolvedAt\" IS NULL) OR (\"Status\" IN ('DONE', 'MISSED') AND \"ResolvedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_RoutineOccurrences_Status", "\"Status\" IN ('PENDING', 'DONE', 'MISSED')");

                            t.HasCheckConstraint("CK_RoutineOccurrences_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.RuleMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AffectedEntityIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<string[]>("AllowedActionTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("ConsequenceCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RuleMatches");
                });

            modelBuilder.Entity("TidySense.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CompletedForLocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectionReasonCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SequenceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GoalId", "UserId");

                    b.HasIndex("ProjectId", "UserId");

                    b.HasIndex("UserId", "CreatedAt", "Id");

                    b.HasIndex("UserId", "GoalId", "Status");

                    b.HasIndex("UserId", "ProjectId", "Status");

                    b.HasIndex("UserId", "SequenceId", "SequenceOrder")
                        .IsUnique()
                        .HasFilter("\"SequenceId\" IS NOT NULL");

                    b.HasIndex("UserId", "Status", "PlannedDate");

                    b.ToTable("Tasks", t =>
                        {
                            t.HasCheckConstraint("CK_Tasks_Deadline", "\"Deadline\" IS NULL OR \"PlannedDate\" IS NULL OR \"PlannedDate\" <= \"Deadline\"");

                            t.HasCheckConstraint("CK_Tasks_ParentExclusive", "NOT (\"GoalId\" IS NOT NULL AND \"ProjectId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Tasks_Protection", "(\"IsProtected\" AND \"ProtectionReasonCode\" = 'USER') OR (NOT \"IsProtected\" AND \"ProtectionReasonCode\" IS NULL)");

                            t.HasCheckConstraint("CK_Tasks_SequencePair", "(\"SequenceId\" IS NULL AND \"SequenceOrder\" IS NULL) OR (\"SequenceId\" IS NOT NULL AND \"SequenceOrder\" IS NOT NULL AND \"SequenceOrder\" > 0)");

                            t.HasCheckConstraint("CK_Tasks_Source", "\"Source\" IN ('MANUAL', 'AI_ASSISTED', 'SYSTEM_MIGRATED')");

                            t.HasCheckConstraint("CK_Tasks_Status", "\"Status\" IN ('ACTIVE', 'COMPLETED', 'DROPPED')");

                            t.HasCheckConstraint("CK_Tasks_TemporalValidity", "\"Status\" <> 'ACTIVE' OR \"GoalId\" IS NOT NULL OR \"ProjectId\" IS NOT NULL OR \"PlannedDate\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Tasks_TerminalState", "(\"Status\" = 'ACTIVE' AND \"TerminalAt\" IS NULL AND \"CompletedForLocalDate\" IS NULL) OR (\"Status\" = 'COMPLETED' AND \"TerminalAt\" IS NOT NULL AND \"CompletedForLocalDate\" IS NOT NULL) OR (\"Status\" = 'DROPPED' AND \"TerminalAt\" IS NOT NULL AND \"CompletedForLocalDate\" IS NULL)");

                            t.HasCheckConstraint("CK_Tasks_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SessionEpoch")
                        .HasColumnType("integer");

                    b.Property<bool>("SetupComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_SessionEpoch", "\"SessionEpoch\" >= 0");
                        });
                });

            modelBuilder.Entity("TidySense.Models.ActionConfirmation", b =>
                {
                    b.HasOne("TidySense.Models.PlanningDraft", null)
                        .WithMany()
                        .HasForeignKey("PlanningDraftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.ReconcileSession", "Session")
                        .WithMany()
                        .HasForeignKey("ReconcileSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TidySense.Models.CaptureItem", b =>
                {
                    b.HasOne("TidySense.Models.User", "User")
                        .WithMany("Captures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TidySense.Models.DomainEvent", b =>
                {
                    b.HasOne("TidySense.Models.CommandResult", null)
                        .WithMany()
                        .HasForeignKey("CommandResultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TidySense.Models.Goal", b =>
                {
                    b.HasOne("TidySense.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TidySense.Models.IdempotencyRecord", b =>
                {
                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.OutboxMessage", b =>
                {
                    b.HasOne("TidySense.Models.DomainEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.PlanningAttempt", b =>
                {
                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.PlanningDraft", b =>
                {
                    b.HasOne("TidySense.Models.PlanningAttempt", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.PlanningDraftRevision", b =>
                {
                    b.HasOne("TidySense.Models.PlanningDraft", "Draft")
                        .WithMany("Revisions")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("TidySense.Models.PlanningFact", b =>
                {
                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TidySense.Models.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TidySense.Models.Project", b =>
                {
                    b.HasOne("TidySense.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TidySense.Models.Goal", "Goal")
                        .WithMany("Projects")
                        .HasForeignKey("GoalId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TidySense.Models.ReconcileFact", b =>
                {
                    b.HasOne("TidySense.Models.ReconcileSession", "Session")
                        .WithMany("Facts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TidySense.Models.ReconcilePrompt", b =>
                {
                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.ReconcileSession", b =>
                {
                    b.HasOne("TidySense.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TidySense.Models.Routine", b =>
                {
                    b.HasOne("TidySense.Models.Routine", "ContinuationOf")
                        .WithMany()
                        .HasForeignKey("ContinuationOfRoutineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TidySense.Models.Goal", "Goal")
                        .WithMany("Routines")
                        .HasForeignKey("GoalId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.Project", "Project")
                        .WithMany("Routines")
                        .HasForeignKey("ProjectId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContinuationOf");

                    b.Navigation("Goal");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TidySense.Models.RoutineOccurrence", b =>
                {
                    b.HasOne("TidySense.Models.Routine", "Routine")
                        .WithMany("Occurrences")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("TidySense.Models.RuleMatch", b =>
                {
                    b.HasOne("TidySense.Models.ReconcileSession", "Session")
                        .WithMany("RuleMatches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TidySense.Models.TaskItem", b =>
                {
                    b.HasOne("TidySense.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TidySense.Models.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TidySense.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Goal");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TidySense.Models.Goal", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Routines");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TidySense.Models.PlanningDraft", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TidySense.Models.Project", b =>
                {
                    b.Navigation("Routines");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TidySense.Models.ReconcileSession", b =>
                {
                    b.Navigation("Facts");

                    b.Navigation("RuleMatches");
                });

            modelBuilder.Entity("TidySense.Models.Routine", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("TidySense.Models.User", b =>
                {
                    b.Navigation("Captures");

                    b.Navigation("Goals");

                    b.Navigation("Projects");

                    b.Navigation("Routines");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
